spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:tcp://localhost/~/test   # H2 접속 정보
    username: ${H2_USERNAME}  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: ${H2_PASSWORD} # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  config:
    import: secret/application-secret.yml